In [ ]:
!pip install git+https://github.com/Mottl/hurst.git
!pip install git+https://github.com/ranaroussi/yfinance.git

Collecting git+https://github.com/Mottl/hurst.git
  Cloning https://github.com/Mottl/hurst.git to /tmp/pip-req-build-yopkq7j9
  Running command git clone --filter=blob:none --quiet https://github.com/Mottl/hurst.git /tmp/pip-req-build-yopkq7j9
  Resolved https://github.com/Mottl/hurst.git to commit 7d0bc11cf7503a9c4cd7733b008bea2d7db3501f
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=0.18 in /usr/local/lib/python3.12/dist-packages (from hurst==0.0.5) (2.2.2)
Requirement already satisfied: numpy>=1.10 in /usr/local/lib/python3.12/dist-packages (from hurst==0.0.5) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.18->hurst==0.0.5) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.18->hurst==0.0.5) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.18->hurst==0.0.5) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.18->hurst==0.0.5) (1.17.0)
Building wheels for collected packages: hurst
  Building wheel for hurst (setup.py) ... done
  Created wheel for hurst: filename=hurst-0.0.5-py3-none-any.whl size=5869 sha256=e32089fac1194b08c2b93f4e35e6a543fdc6ac7295e7a32fcb558b1354147e7d
  Stored in directory: /tmp/pip-ephem-wheel-cache-bd9s0fsy/wheels/8d/75/c2/52a1b52d5814c29a9496218e924cb9b9ba17ea4a677ad21f83
Successfully built hurst
Installing collected packages: hurst
Successfully installed hurst-0.0.5
Collecting git+https://github.com/ranaroussi/yfinance.git
  Cloning https://github.com/ranaroussi/yfinance.git to /tmp/pip-req-build-82mm92v4
  Running command git clone --filter=blob:none --quiet https://github.com/ranaroussi/yfinance.git /tmp/pip-req-build-82mm92v4
  Resolved https://github.com/ranaroussi/yfinance.git to commit 81631009a20bf682dc3d6799e954fb49af770580
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance==1.2.0) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance==1.2.0) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance==1.2.0) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance==1.2.0) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance==1.2.0) (4.9.2)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance==1.2.0) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance==1.2.0) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance==1.2.0) (4.0.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance==1.2.0) (4.13.5)
Collecting curl_cffi<0.14,>=0.7 (from yfinance==1.2.0)
  Downloading curl_cffi-0.13.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance==1.2.0) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance==1.2.0) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance==1.2.0) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance==1.2.0) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi<0.14,>=0.7->yfinance==1.2.0) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi<0.14,>=0.7->yfinance==1.2.0) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance==1.2.0) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance==1.2.0) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance==1.2.0) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance==1.2.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance==1.2.0) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance==1.2.0) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance==1.2.0) (1.17.0)
Downloading curl_cffi-0.13.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 46.9 MB/s eta 0:00:00
Building wheels for collected packages: yfinance
  Building wheel for yfinance (setup.py) ... done
  Created wheel for yfinance: filename=yfinance-1.2.0-py2.py3-none-any.whl size=130142 sha256=3777aa270243a3988e4b8d0392d62f434e66b9814642c172693ba33c59586fb7
  Stored in directory: /tmp/pip-ephem-wheel-cache-ry5cato_/wheels/10/84/01/c0b6e111c5af445cb9c523399c6e0acba700394426760f67b1
Successfully built yfinance
Installing collected packages: curl_cffi, yfinance
  Attempting uninstall: curl_cffi
    Found existing installation: curl_cffi 0.14.0
    Uninstalling curl_cffi-0.14.0:
      Successfully uninstalled curl_cffi-0.14.0
  Attempting uninstall: yfinance
    Found existing installation: yfinance 0.2.66
    Uninstalling yfinance-0.2.66:
      Successfully uninstalled yfinance-0.2.66
Successfully installed curl_cffi-0.13.0 yfinance-1.2.0

In [ ]:
# --- SETUP & IMPORTS ---
from google.colab import drive
import sys
import os
import json
import joblib
import pandas as pd
import numpy as np
import yfinance as yf
import torch
import torch.nn.functional as F
import xgboost as xgb
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from sentence_transformers import CrossEncoder
import warnings
from datetime import datetime

# 1. Montar Drive
drive.mount('/content/drive', force_remount=True)

# 2. Configurar Rutas
BASE_PATH = '/content/drive/MyDrive/Challenges_ML-DL'
MODELS_PATH = os.path.join(BASE_PATH, 'models')

# Agregar al path para importar utils
if BASE_PATH not in sys.path:
    sys.path.append(BASE_PATH)

# Importar funciones personalizadas
try:
    from utils_2 import (
        LSTMMixedModel,
        calculate_rolling_hurst_numpy,
        find_optimal_d,
        frac_diff_ffd,
        yang_zhang_volatility,
        get_drift,
        calculate_amihud_illiquidity,
        calculate_vp_divergence_robust,
        apply_robust_normalization,
        get_sentiment_logits,
        calculate_bayesian_final_probability,
        get_barrier_probabilities,
        engineer_features
    )
    print("✅ utils.py importado correctamente.")
except ImportError as e:
    print(f"❌ Error importando utils: {e}")

# Configuración Global
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Usando dispositivo: {device}")
warnings.filterwarnings('ignore')

Mounted at /content/drive
✅ utils.py importado correctamente.
Usando dispositivo: cpu

In [ ]:
# --- CONFIGURACIÓN DE SECTORES ---
# Aquí centralizamos toda la información específica de cada sector
SECTORS_CONFIG = {
    "TECH": {
        "model_files": {
            "lstm": "tech_us_model.pth",
            "scaler": "scalers_tech_us.pkl",
            "meta": "meta_model_xgb_tech.json",
            "lstm_hourly": "tech_us_model_hourly.pth",
            "scaler_hourly": "scalers_tech_us_hourly.pkl",
            "meta_hourly": "meta_model_xgb_tech_hourly.json"
        },
        "bayesian": {
            "p_call": 0.3965, "p_put": 0.3918,
            "sensitivity": 0.2, "specificity": 0.92
        },
        "bayesian_hourly": {
            "p_call": 0.4305, "p_put": 0.4031,
            "sensitivity": 0.42, "specificity": 0.84
        },
        "tickers": ["QQQ", "META", "AAPL", "AMZN", "NFLX", "TSLA", "NVDA", "PLTR", "MSFT", "GOOGL", "INTC", "AMD"],
        "keywords": {
            "QQQ": ["Invesco QQQ Trust", "Nasdaq 100", "NDX", "Technology Sector ETF", "Tech stocks", "Growth stocks"],
            "META": ["META", "Facebook", "Meta Platforms", "Instagram", "WhatsApp", "Mark Zuckerberg", "Metaverse", "Reality Labs", "Llama", "Reels"],
            "AAPL": ["AAPL", "Apple", "iPhone", "Mac", "Tim Cook", "App Store", "Services", "Apple Intelligence", "Vision Pro"],
            "AMZN": ["AMZN", "Amazon", "AWS", "Cloud Computing", "E-commerce", "Jeff Bezos", "Andy Jassy", "Prime", "Logistics"],
            "NFLX": ["NFLX", "Netflix", "Streaming service", "Subscriber growth", "Ted Sarandos", "Ad-supported", "Password sharing"],
            "TSLA": ["TSLA", "Tesla", "Elon Musk", "Electric Vehicles", "Cybertruck", "FSD", "Robotaxi", "Energy storage", "Optimus"],
            "NVDA": ["NVDA", "Nvidia", "Jensen Huang", "GPU", "Data Center", "AI chips", "Blackwell", "H100", "CUDA"],
            "PLTR": ["PLTR", "Palantir", "Alex Karp", "Big Data Analytics", "Gotham", "Foundry", "AIP", "Bootcamps", "Commercial revenue"],
            "MSFT": ["MSFT", "Microsoft", "Satya Nadella", "Azure", "Windows", "Copilot", "OpenAI", "Activision", "Office 365"],
            "GOOGL": ["GOOGL", "Alphabet", "Google", "Sundar Pichai", "Google Cloud", "Gemini", "YouTube", "Waymo", "Search", "DeepMind"],
            "INTC": ["INTC", "Intel", "Pat Gelsinger", "Xeon", "Intel Foundry", "Gaudi", "CHIPS Act", "18A"],
            "AMD": ["AMD", "Advanced Micro Devices", "Lisa Su", "Ryzen", "EPYC", "Radeon", "MI300", "Instinct", "Data Center"]
        }
    },
    "BANKS": {
        "model_files": {
            "lstm": "banks_model.pth",
            "scaler": "scalers_banks.pkl",
            "meta": "meta_model_xgb_banks.json",
            "lstm_hourly": "banks_model_hourly.pth",
            "scaler_hourly": "scalers_banks_hourly.pkl",
            "meta_hourly": "meta_model_xgb_banks_hourly.json"
        },
        "bayesian": {
            "p_call": 0.4199, "p_put": 0.394,
            "sensitivity": 0.32, "specificity": 0.89
        },
        "bayesian_hourly": {
            "p_call": 0.5163, "p_put": 0.4631,
            "sensitivity": 0.61, "specificity": 0.75
        },
        "tickers": ["BAC", "JPM", "WFC", "C", "XLF", "TNA"],
        "keywords": {
            "BAC": ["BAC", "Bank of America", "BofA", "Brian Moynihan", "Merrill Lynch", "Merrill", "Federal Reserve"],
            "JPM": ["JPM", "JPMorgan", "JP Morgan", "Chase", "Jamie Dimon", "First Republic", "Investment Banking", "Federal Reserve"],
            "WFC": ["WFC", "Wells Fargo", "Charlie Scharf", "Commercial Banking", "Mortgage", "Asset Cap", "Federal Reserve"],
            "C": ["Citigroup", "Citi", "Jane Fraser", "Wealth Management", "Banamex", "Federal Reserve"],
            "XLF": ["XLF", "Financial Select Sector SPDR", "Financials ETF", "S&P 500 Financials", "Banking Sector", "Interest Rates", "Federal Reserve", "Berkshire Hathaway"],
            "TNA": ["TNA", "Direxion Daily Small Cap Bull", "Russell 2000", "Small Caps", "Leveraged ETF", "Risk-on", "IWM", "Regional Banks", "Federal Reserve"]
        }
    },
    # "OIL": {
    #     "model_files": {
    #         "lstm": "petroleo_model.pth",
    #         "scaler": "scalers_petroleo.pkl",
    #         "meta": "meta_model_xgb_petroleo.json",
    #         "lstm_hourly": "petroleo_model_hourly.pth",
    #         "scaler_hourly": "scalers_petroleo_hourly.pkl",
    #         "meta_hourly": "meta_model_xgb_petroleo_hourly.json"
    #     },
    #     "bayesian": {
    #         "p_call": 0.41, "p_put": 0.42,
    #         "sensitivity": 0.29, "specificity": 0.83
    #     },
    #     "bayesian_hourly": {
    #         "p_call": 0.4748, "p_put": 0.4375,
    #         "sensitivity": 0.54, "specificity": 0.75
    #     },
    #     "tickers": ["CVX", "XOM", "USO"],
    #     "keywords": {
    #         "CVX": ["Chevron", "Mike Wirth", "Permian Basin", "Tengiz", "Oil & Gas"],
    #         "XOM": ["ExxonMobil", "Exxon", "Darren Woods", "Upstream", "Energy"],
    #         "USO": ["United States Oil Fund", "WTI Crude", "Oil prices", "Petroleum"]
    #     }
    # },
    "MINING": {
        "model_files": {
            "lstm": "mining_model.pth",
            "scaler": "scalers_mining.pkl",
            "meta": "meta_model_xgb_mining.json",
            "lstm_hourly": "mining_model_hourly.pth",
            "scaler_hourly": "scalers_mining_hourly.pkl",
            "meta_hourly": "meta_model_xgb_mining_hourly.json"
        },
        "bayesian": {
            "p_call": 0.3896, "p_put": 0.3783,
            "sensitivity": 0.16, "specificity": 0.92
        },
        "bayesian_hourly": {
            "p_call": 0.5261, "p_put": 0.52,
            "sensitivity": 0.65, "specificity": 0.68
        },
        "tickers": ["GLD", "SLV", "NEM", "HL", "PAAS", "NUE", "CLF"],
        "keywords": {
            "GLD": ["GLD", "SPDR Gold Shares", "Gold", "Gold Futures", "Bullion", "Precious Metals", "Safe haven", "Inflation hedge", "Central Banks", "Geopolitical risk", "Real rates"],
            "SLV": ["SLV", "iShares Silver Trust", "Silver", "Silver Futures", "Industrial metals", "Solar energy", "Photovoltaic", "Electronics", "Gold/Silver ratio", "Precious Metals"],
            "NEM": ["NEM", "Newmont", "Gold mining", "Tom Palmer", "Newcrest", "Precious metals", "Gold miners"],
            "HL": ["HL", "Hecla", "Hecla Mining", "Silver mining", "Greens Creek", "Lucky Friday", "Primary silver"],
            "PAAS": ["PAAS", "Pan American Silver", "Silver mining", "Yamana Gold", "Latin America mining", "Precious metals"],
            "NUE": ["NUE", "Nucor", "Steel", "Steelmaker", "Electric Arc Furnace", "EAF", "Scrap metal", "Infrastructure"],
            "CLF": ["CLF", "Cleveland-Cliffs", "Lourenco Goncalves", "Steel", "Iron ore", "Blast furnace", "Automotive steel", "Infrastructure"]
        }
    }
}

In [ ]:
# --- CARGA DE MODELOS COMPARTIDOS (NLP) ---
print("Cargando modelos de NLP...")
model_name = "mrm8488/deberta-v3-ft-financial-news-sentiment-analysis"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model_deberta = AutoModelForSequenceClassification.from_pretrained(model_name)
model_deberta.to(device)
model_deberta.eval()

relevance_model = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')
print("✅ Modelos de NLP cargados.")

Cargando modelos de NLP...

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/23.0 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

special_tokens_map.json:   0%|          | 0.00/286 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/568M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-6-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

✅ Modelos de NLP cargados.

In [ ]:
# --- INFERENCIA UNIFICADA ---
SEQ_LEN_2d = 20
SEQ_LEN_hourly = 40
TBM_HORIZON = 2
k = 1
all_inference_results = []

TBM_HORIZON_hourly = 10

for sector_name, config in SECTORS_CONFIG.items():
    print(f"\n{'='*50}")
    print(f"🚀 INICIANDO INFERENCIA SECTOR: {sector_name}")
    print(f"{'='*50}")

    # 1. Cargar Modelos Específicos del Sector
    try:
        # LSTM
        lstm_path = os.path.join(MODELS_PATH, config['model_files']['lstm'])
        model = LSTMMixedModel(num_features=23, lstm_hidden=64, dropout=0.3).to(device)
        model.load_state_dict(torch.load(lstm_path, map_location=device))
        model.eval()

        # LSTM_hourly
        lstm_hourly_path = os.path.join(MODELS_PATH, config['model_files']['lstm_hourly'])
        model_hourly = LSTMMixedModel(num_features=23, lstm_hidden=64, dropout=0.3).to(device)
        model_hourly.load_state_dict(torch.load(lstm_hourly_path, map_location=device))
        model_hourly.eval()

        # Meta-Model (XGB)
        meta_path = os.path.join(MODELS_PATH, config['model_files']['meta'])
        meta_model = xgb.XGBClassifier()
        meta_model.load_model(meta_path)

        # Meta-Model_hourly (XGB)
        meta_hourly_path = os.path.join(MODELS_PATH, config['model_files']['meta_hourly'])
        meta_model_hourly = xgb.XGBClassifier()
        meta_model_hourly.load_model(meta_hourly_path)

        # Scalers
        scaler_path = os.path.join(MODELS_PATH, config['model_files']['scaler'])
        scalers = joblib.load(scaler_path)

        # Scalers_hourly
        scaler_hourly_path = os.path.join(MODELS_PATH, config['model_files']['scaler_hourly'])
        scalers_hourly = joblib.load(scaler_hourly_path)


        print(f"✅ Modelos cargados para {sector_name}")

    except FileNotFoundError as e:
        print(f"❌ Error cargando archivos para {sector_name}: {e}")
        continue

    # 2. Configurar Probabilidades Bayesianas
    b_params = config['bayesian']
    b_params_hourly = config['bayesian_hourly']

    # 3. Iterar Tickers
    for ticker in config['tickers']:
            print(f"🔹 Procesando: {ticker} ...")
            y_ticker = yf.Ticker(ticker)
            hist = y_ticker.history(period="max")
            hist_hourly = y_ticker.history(period="730d", interval="1h")

            if hist.empty: continue

            hist.index = pd.to_datetime(hist.index, utc=True)
            df_raw = hist.copy()
            df_raw_hourly = hist_hourly.copy()

            # --- FEATURE ENGINEERING ---
            df, full_df = engineer_features(df_raw, hist['Close'])
            df_hourly, full_df_hourly = engineer_features(df_raw_hourly, hist_hourly['Close'])

            if full_df is None or len(full_df) < SEQ_LEN_2d + 20:
                continue

            # --- PREDICCIÓN ---
            X_inference = full_df.values[-SEQ_LEN_2d:].reshape(1, SEQ_LEN_2d, -1)
            X_inference_hourly = full_df_hourly.values[-SEQ_LEN_hourly:].reshape(1, SEQ_LEN_hourly, -1)

            if ticker not in scalers:
                print(f"⚠️ No hay scaler para {ticker}")
                continue

            X_inference = apply_robust_normalization(X_inference, scalers[ticker])
            X_inference_hourly = apply_robust_normalization(X_inference_hourly, scalers_hourly[ticker])
            X_inference_tensor = torch.tensor(X_inference, dtype=torch.float32).to(device)
            X_inference_tensor_hourly = torch.tensor(X_inference_hourly, dtype=torch.float32).to(device)

            logits, _ = model(X_inference_tensor)
            probs = F.softmax(logits, dim=1)
            pred = torch.argmax(logits, dim=1)
            pred_primary = pred[0].item()

            logits_hourly, _ = model_hourly(X_inference_tensor_hourly)
            probs_hourly = F.softmax(logits_hourly, dim=1)
            pred_hourly = torch.argmax(logits_hourly, dim=1)
            pred_primary_hourly = pred_hourly[0].item()

            if pred_primary == 0 and pred_primary_hourly == 0: continue

            # --- META-MODEL VALIDATION ---
            with torch.no_grad():
                x_raw_feat = X_inference_tensor[0, -10:, :].flatten()
                x_meta_model = torch.cat((probs[0], x_raw_feat)).cpu().numpy().reshape(1, -1)
                meta_pred = meta_model.predict(x_meta_model)

                x_raw_feat_hourly = X_inference_tensor_hourly[0, -10:, :].flatten()
                x_meta_model_hourly = torch.cat((probs_hourly[0], x_raw_feat_hourly)).cpu().numpy().reshape(1, -1)
                meta_pred_hourly = meta_model_hourly.predict(x_meta_model_hourly)

            # Barreras
            p_t = df['Close'].values[-1]
            vol_t = df['vol_20'].values[-1]
            drift_val = df['drift'].values[-1]
            step_sqrt = np.sqrt(TBM_HORIZON)
            deviation = (drift_val - 0.5 * vol_t**2) * TBM_HORIZON

            upper_barrier = p_t * np.exp(deviation + k * vol_t * step_sqrt)
            lower_barrier = p_t * np.exp(deviation - k * vol_t * step_sqrt)

            is_call = (pred_primary == 1) and (upper_barrier > (p_t * 1.01))
            is_put = (pred_primary == 2) and (lower_barrier < (p_t * 0.99))

            # Barreras_hourly
            p_t_hourly = df_hourly['Close'].values[-1]
            vol_t_hourly = df_hourly['vol_20'].values[-1]
            drift_val_hourly = df_hourly['drift'].values[-1]
            step_sqrt_hourly = np.sqrt(TBM_HORIZON_hourly)
            deviation_hourly = (drift_val_hourly - 0.5 * vol_t_hourly**2) * TBM_HORIZON_hourly

            upper_barrier_hourly = p_t_hourly * np.exp(deviation_hourly + k * vol_t_hourly * step_sqrt_hourly)
            lower_barrier_hourly = p_t_hourly * np.exp(deviation_hourly - k * vol_t_hourly * step_sqrt_hourly)

            is_call_hourly = (pred_primary_hourly == 1) and (upper_barrier_hourly > (p_t_hourly * 1.01))
            is_put_hourly = (pred_primary_hourly == 2) and (lower_barrier_hourly < (p_t_hourly * 0.99))

            if is_call or is_put or is_call_hourly or is_put_hourly:
                # Determine main op_type
                if is_call or is_call_hourly:
                    op_type = "call"
                    target_type = 1
                    barrier = upper_barrier if is_call else upper_barrier_hourly
                    barrier_hourly = upper_barrier_hourly
                else:
                    op_type = "put"
                    target_type = 2
                    barrier = lower_barrier if is_put else lower_barrier_hourly
                    barrier_hourly = lower_barrier_hourly

                mov_type = "alcista" if op_type == "call" else "bajista"
                print(f"⚡ OPORTUNIDAD: {ticker} ({op_type.upper()}) | Barrera: {barrier:.2f}")
                print(f"⚡ Mov. en hrs: {ticker} ({mov_type.upper()}) | Barrera: {barrier_hourly:.2f}")

                # Sentiment Analysis
                news = y_ticker.news
                logits_sent = get_sentiment_logits(news, ticker, config['keywords'], relevance_model, tokenizer, model_deberta, device)

                probs_news = np.array([])
                if logits_sent is not None:
                    probs_news = F.softmax(logits_sent, dim=1).detach().cpu().numpy()

                # Datos Mercado
                barrier_prob = get_barrier_probabilities(y_ticker, barrier, op_type)

                if not barrier_prob.empty:
                    precision_base = b_params['p_call'] if target_type == 1 else b_params['p_put']
                    recall_meta = b_params['sensitivity']
                    spec_meta = b_params['specificity']

                    precision_base_hourly = b_params_hourly['p_call'] if target_type == 1 else b_params_hourly['p_put']
                    recall_meta_hourly = b_params_hourly['sensitivity']
                    spec_meta_hourly = b_params_hourly['specificity']

                    for idx, row in barrier_prob.iterrows():
                        p_final, score = calculate_bayesian_final_probability(
                            target_type=target_type,
                            pred_primary=pred_primary,
                            meta_pred=meta_pred[0],
                            precision_base=precision_base,
                            recall_meta=recall_meta,
                            spec_meta=spec_meta,
                            pred_primary_hourly=pred_primary_hourly,
                            meta_pred_hourly=meta_pred_hourly[0],
                            precision_base_hourly=precision_base_hourly,
                            recall_meta_hourly=recall_meta_hourly,
                            spec_meta_hourly=spec_meta_hourly,
                            probs_news=probs_news,
                            p_market=row['Prob. Toca Strike'],
                            w_market=0.3
                        )

                        result_data = {
                            "Fecha": datetime.now().strftime("%Y-%m-%d"),
                            "Sector": sector_name,
                            "Ticker": ticker,
                            "Tipo": op_type.upper(),
                            "Precio Actual": round(p_t, 2),
                            "Barrera": round(barrier, 2),
                            "Barrera a 10 hrs": round(barrier_hourly, 2),
                            "Vencimiento": row['Vencimiento'],
                            "Strike": row['Strike Seleccionado'],
                            "Ask": row['Ask'],
                            "IV": row['IV'],
                            "Prob. Mercado": row['Prob. Toca Strike'],
                            "Prob. Final (Bayes)": round(p_final, 4),
                            "Sentimiento Score": round(score, 4)
                        }
                        all_inference_results.append(result_data)
                        pd.set_option('display.max_columns', None)
                        display(pd.DataFrame([result_data]))


# --- GUARDAR RESULTADOS ---
if all_inference_results:
    df_results = pd.DataFrame(all_inference_results)
    excel_path = 'Inference_Results.xlsx'
    df_results.to_excel(excel_path, index=False)
    print(f"\n✅ Resultados procesados y guardados en: {excel_path}")
    display(df_results)
else:
    print("\n⚠️ No se encontraron oportunidades que cumplan los criterios.")

==================================================
🚀 INICIANDO INFERENCIA SECTOR: TECH
==================================================
✅ Modelos cargados para TECH
🔹 Procesando: QQQ ...
⚡ OPORTUNIDAD: QQQ (CALL) | Barrera: 608.86
⚡ Mov. en hrs: QQQ (ALCISTA) | Barrera: 607.62
--- FIltrando noticias para QQQ ---
TQQQ has delivered a 47.69% gain over the past year and 2,653.53% over the past decade. Those numbers explain why retail investors keep coming back to it. The appeal is simple: own the Nasdaq-100, but with the accelerator pressed to the floor. In a sustained bull market, that logic works extraordinarily well. The problem is ... TQQQ Holders Face a Risk That Has Nothing to Do With the Nasdaq Falling
The broad market exchange-traded fund SPDR S&P 500 ETF Trust (SPY) was down 0.5% and the actively tr
Several sector ETFs, including WCLD, XTL and XOP, are holding steady and even gaining despite market volatility tied to Middle East tensions.

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,QQQ,CALL,599.75,608.86,607.62,2026-03-20,604.0,11.89,0.32,0.8957,0.7561,0.329

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,QQQ,CALL,599.75,608.86,607.62,2026-03-27,604.0,14.0,0.293,0.9142,0.7604,0.329

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,QQQ,CALL,599.75,608.86,607.62,2026-03-31,604.0,14.91,0.281,0.9216,0.7621,0.329

🔹 Procesando: META ...
⚡ OPORTUNIDAD: META (CALL) | Barrera: 662.24
⚡ Mov. en hrs: META (ALCISTA) | Barrera: 660.25
--- FIltrando noticias para META ---
Meta and other tech stocks have faced headwinds in recent weeks.
Meta Platforms signed multi year AI chip and infrastructure agreements with Nvidia, AMD, and Google to support its next generation AI systems. The company is pursuing a major data center expansion, including a potential site in Texas that previously had interest from Oracle and OpenAI, with Nvidia involved in facilitating a possible lease. Meta also secured a content licensing deal with News Corp to use premium news content for AI training across its platforms. For investors tracking...
Hedge funds and institutional investors have been quietly building positions in Meta Platforms (NASDAQ:META) despite recent market volatility, viewing it as one of the most compelling opportunities in the AI and digital advertising space. With its massive user base, dominant ad business, and aggressive push into generative AI, Meta has attracted significant buying interest from ... Billionaires Are Loading Up on This 1 Stock That Wall Street Says Has 31% Upside
Oracle and OpenAI have canceled plans to expand a flagship AI data center project in Abilene, Texas, after negotiations over financing and project scope stalled. The decision comes as Oracle announces large-scale layoffs and cost-cutting tied to the financial pressure of rapid AI infrastructure investment. The canceled expansion could open space for Meta as a potential tenant, with Nvidia involved in facilitating a transition at the site. Oracle, traded as NYSE:ORCL, is in the spotlight as...

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,META,CALL,644.86,662.24,660.25,2026-03-20,652.5,15.05,0.397,0.8523,0.076,0.014

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,META,CALL,644.86,662.24,660.25,2026-03-27,655.0,17.95,0.383,0.8412,0.0751,0.014

🔹 Procesando: AAPL ...
⚡ OPORTUNIDAD: AAPL (PUT) | Barrera: 251.64
⚡ Mov. en hrs: AAPL (BAJISTA) | Barrera: 250.33
--- FIltrando noticias para AAPL ---
Apple's MacBook Neo is a threat to Microsoft's PC empire and the Google Chromebook's grip on the education market.
Apple launches MacBook Neo, its most affordable laptop, alongside a refreshed iPad Air and entry-level iPhone 17e. The new devices focus on AI powered features and are aimed at students, first time Mac buyers, and price sensitive markets. The lineup targets segments traditionally dominated by Chromebooks and budget Windows PCs. For investors watching NasdaqGS:AAPL, these product moves come with the stock trading at $257.46. The share price is down 5.0% year to date and has seen a 7.4%...
The launch of MacBook Neo — the most affordable laptop ever from Apple Inc. — could slightly lift overall revenue while helping the tech giant win over a new generation of student users, according to analyst Gene Munster. Apple Targets Students With Its Cheapest Mac Yet On Wednesday, Apple unveiled the MacBook Neo with a starting price of $599, or $499 for education customers, marking a dramatic drop from the previous entry-level Mac price of about $999. The new 13-inch laptop runs on the Apple

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,AAPL,PUT,257.46,251.64,250.33,2026-03-20,255.0,5.45,0.357,0.8843,0.0716,-0.0358

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,AAPL,PUT,257.46,251.64,250.33,2026-03-27,255.0,6.5,0.329,0.9008,0.073,-0.0358

🔹 Procesando: AMZN ...
⚡ OPORTUNIDAD: AMZN (CALL) | Barrera: 219.52
⚡ Mov. en hrs: AMZN (ALCISTA) | Barrera: 219.52
--- FIltrando noticias para AMZN ---
Rockland Trust VP and portfolio manager Michael Sayers sits down with Josh Lipton to explain why he's looking favorably on shares of Lululemon (LULU) — for the athleisure brand's expected announcement of a new CEO — and Amazon (AMZN) on the growth of its AWS segment. To watch more expert insights and analysis on the latest market action, check out more&nbsp;Market Domination.
Amazon has been the worst-performing "Magnificent Seven" stock over the last five years. Don't bet on that happening again.
Amazon is betting big on AI infrastructure, and Nvidia is shaping up to be one of the biggest beneficiaries.
Amazon stock has lost about 7% year to date, at the time of writing, Friday afternoon, March 6, according to Yahoo Finance. Meanwhile, the SPDR S&P 500 index (SPY) is down about a little more than 1% in the same period. Alphabet (GOOGL) is down almost 5%.Microsoft (MSFT) is down 15%.Apple ...
Two months ago, Wall Street analysts triggered a sharp sell-off in Marvell Technology (NASDAQ:MRVL) shares. Fears that the company could lose major hyperscaler customers such as Amazon (NASDAQ:AMZN) and Microsoft (NASDAQ:MSFT) to rivals sent the stock tumbling 7% in a single session. Over the ensuing weeks, MRVL shed roughly 20% of its value as concerns ... Wall Street’s Worry About Marvell Losing Customers Was Overblown

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,AMZN,CALL,213.21,219.52,219.52,2026-03-20,217.5,4.9,0.441,0.7786,0.1871,-0.3963

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,AMZN,CALL,213.21,219.52,219.52,2026-03-27,215.0,7.55,0.434,0.9105,0.2136,-0.3963

🔹 Procesando: NFLX ...
🔹 Procesando: TSLA ...
⚡ OPORTUNIDAD: TSLA (CALL) | Barrera: 407.48
⚡ Mov. en hrs: TSLA (ALCISTA) | Barrera: 405.43
--- FIltrando noticias para TSLA ---
Ford Motor Company has stopped production of several electric vehicles and de-emphasized a former large portion of its growth strategy. In a recent interview, Ford CEO Jim Farley says he would have done things differently. Ford CEO Has Some Regrets Serving as CEO of Ford since October 2020, Farley has guided the company through periods of growth, but also watched profitability hurt by focusing on electric vehicle unit growth. Farley sees electric vehicles as a future point of growth, but right n
Tesla Inc. has recorded an uptick in its reported registrations across multiple markets in the European region, in what could be a boost for the company amid falling sales. Registrations Surge 10% On Thursday, Electrek compiled registration data from 15 different territories in the region, including France, UK, Germany, Portugal and more. The company, in total, reported 17,425 registrations in February, representing a 10% YoY surge from February 2025. Don't Miss: Explore the Fire-Safe Energy Sto
Elon Musk in 2020 posted a message that sounded like a radical shift in how one of the world's richest people planned to live. “I am selling almost all physical possessions,” he wrote on Twitter, now X. “Will own no house.” However, a recent The New York Times report suggests something very different happened behind the scenes after Musk moved from California to Texas. According to the Times report, which was based on millions of business filings and property records across Texas, Musk quietly b
On Thursday, Maye Musk shared an emotional story about a photographer who credited Elon Musk and Tesla Inc. with saving his family's lives. Photographer Shares Tesla Crash Survival Story During an interview shared by Tesla Club Austria, Maye Musk recounted a moment that took place during a large photoshoot for Sports Illustrated. According to her, the photographer addressed the room before the shoot began and shared a deeply personal story about a crash involving a Tesla. "He said, ‘I need to sa
TSLY paid out more than $10.78 in distributions in 2024 alone, with an annualized yield cited as high as 75.31%. Generating that income requires a covered call structure that caps upside and leaves downside fully exposed, and understanding that tradeoff is what separates investors who use this fund correctly from those who get hurt by ... YieldMax’s TSLA Option Income ETF Has a 60%+ Yield And a Track Record That Should Terrify You
Tesla is shifting a portion of its Fremont factory to produce its Optimus humanoid robots, marking a move further into robotics and artificial general intelligence. The company is planning for large scale production, with a stated goal of up to 1,000,000 Optimus units per year and a Gen 3 robot reveal on the horizon. Elon Musk has stated that Tesla could be first to achieve embodied AGI, positioning Optimus at the core of the company’s long term vision. Tesla (NasdaqGS:TSLA), trading at...

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,TSLA,CALL,396.73,407.48,405.43,2026-03-20,402.5,11.6,0.495,0.8449,0.6295,0.073

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,TSLA,CALL,396.73,407.48,405.43,2026-03-27,400.0,15.9,0.482,0.9125,0.6492,0.073

🔹 Procesando: NVDA ...
⚡ OPORTUNIDAD: NVDA (CALL) | Barrera: 183.50
⚡ Mov. en hrs: NVDA (ALCISTA) | Barrera: 181.58
--- FIltrando noticias para NVDA ---
⚠️ Ninguna noticia pasó el filtro de relevancia para NVDA.

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,NVDA,CALL,177.82,183.5,181.58,2026-03-20,180.0,6.45,0.573,0.8737,0.076,0.0

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,NVDA,CALL,177.82,183.5,181.58,2026-03-27,180.0,7.7,0.532,0.8856,0.077,0.0

🔹 Procesando: PLTR ...
⚡ OPORTUNIDAD: PLTR (CALL) | Barrera: 163.88
⚡ Mov. en hrs: PLTR (ALCISTA) | Barrera: 168.35
--- FIltrando noticias para PLTR ---
On Thursday, Peter Thiel met with Japanese Prime Minister Sanae Takaichi in Tokyo to discuss emerging technology cooperation as Palantir Technologies strengthens its presence in Japan and broader U.S.–Japan tech ties continue to grow. Thiel And Takaichi Discuss Future Of Advanced Technologies Thiel, co-founder and chairman of Palantir, held talks with Takaichi during a visit to Tokyo, according to Japan's Prime Minister's office. 米パランティア・テクノロジーズ社共同創業者兼会長のピーター・ティール氏の表敬を受けました。日米の先端技術分野の現状及び展望等について
The ongoing sell-off in software stocks has taken a major toll on Palantir investors.
The Pentagon has banned Anthropic's Claude AI across defense work, labeling it a national security threat. Palantir Technologies (NasdaqGS:PLTR) is affected because several government AI platforms, including Maven Smart Systems, use Claude. The ban forces Palantir to rapidly rework core AI workflows for US defense contracts, with potential operational and revenue impact. For you as an investor, this goes to the heart of what Palantir does. The company builds data and AI platforms for...
Palantir Technologies Inc. (NASDAQ:PLTR) is one of the 13 Most Profitable Growth Stocks to Buy Right Now. On February 26, Palantir Technologies Inc. (NASDAQ:PLTR) was initiated at Rosenblatt Securities with a Buy rating. John McPeake from Rosenblatt Securities assigned a price target of $150 to the stock. The firm described Palantir Technologies Inc. (NASDAQ:PLTR) as […]
These Wall Street analysts are forecasting major losses for Palantir and Micron shareholders.
The S&P 500 (SPY) fell nearly 2% on the week, while the Nasdaq 100 dropped about 1.2% and the Russell 2000 small-cap index tumbled over 4%. The VIX fear gauge climbed to 29.49, and is now up 70% in the past month, reflecting genuine investor unease. Geopolitical tension in the Middle East, tariff uncertainty, and a ... S&P 500 Movers: Trade Desk Surges on CEO Buy, Palantir Rides Geopolitical Wave, CrowdStrike Earnings Impress

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,PLTR,CALL,157.16,163.88,168.35,2026-03-20,160.0,5.75,0.613,0.8344,0.0417,-0.2847

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,PLTR,CALL,157.16,163.88,168.35,2026-03-27,160.0,7.25,0.591,0.8528,0.0427,-0.2847

🔹 Procesando: MSFT ...
⚡ OPORTUNIDAD: MSFT (CALL) | Barrera: 415.52
⚡ Mov. en hrs: MSFT (ALCISTA) | Barrera: 419.72
--- FIltrando noticias para MSFT ---
Amazon stock has lost about 7% year to date, at the time of writing, Friday afternoon, March 6, according to Yahoo Finance. Meanwhile, the SPDR S&P 500 index (SPY) is down about a little more than 1% in the same period. Alphabet (GOOGL) is down almost 5%.Microsoft (MSFT) is down 15%.Apple ...
Two months ago, Wall Street analysts triggered a sharp sell-off in Marvell Technology (NASDAQ:MRVL) shares. Fears that the company could lose major hyperscaler customers such as Amazon (NASDAQ:AMZN) and Microsoft (NASDAQ:MSFT) to rivals sent the stock tumbling 7% in a single session. Over the ensuing weeks, MRVL shed roughly 20% of its value as concerns ... Wall Street’s Worry About Marvell Losing Customers Was Overblown

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,MSFT,CALL,408.96,415.52,419.72,2026-03-20,412.5,8.8,0.353,0.881,0.0002,-0.9946

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,MSFT,CALL,408.96,415.52,419.72,2026-03-27,410.0,12.4,0.347,0.9655,0.0003,-0.9946

🔹 Procesando: GOOGL ...
⚡ OPORTUNIDAD: GOOGL (CALL) | Barrera: 305.27
⚡ Mov. en hrs: GOOGL (ALCISTA) | Barrera: 301.39
--- FIltrando noticias para GOOGL ---
Google's parent company is making all the right moves to corner the AI market, which makes it a safer bet than anything you'll see on a prediction market.
Meta Platforms signed multi year AI chip and infrastructure agreements with Nvidia, AMD, and Google to support its next generation AI systems. The company is pursuing a major data center expansion, including a potential site in Texas that previously had interest from Oracle and OpenAI, with Nvidia involved in facilitating a possible lease. Meta also secured a content licensing deal with News Corp to use premium news content for AI training across its platforms. For investors tracking...
Amazon stock has lost about 7% year to date, at the time of writing, Friday afternoon, March 6, according to Yahoo Finance. Meanwhile, the SPDR S&P 500 index (SPY) is down about a little more than 1% in the same period. Alphabet (GOOGL) is down almost 5%.Microsoft (MSFT) is down 15%.Apple ...
Alphabet, the parent company of Google (NasdaqGS:GOOGL), is facing its first wrongful death lawsuit tied to its Gemini AI chatbot. The complaint claims Gemini reinforced harmful content and did not prevent a user from self-harm, leading to a fatal outcome. The case brings fresh attention to legal responsibility and safety protocols for generative AI tools used by consumers. Alphabet runs a broad portfolio that includes Google Search, YouTube, Android, cloud services and an expanding set of...

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,GOOGL,CALL,298.52,305.27,301.39,2026-03-20,302.5,6.8,0.399,0.8361,0.1747,0.064

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,GOOGL,CALL,298.52,305.27,301.39,2026-03-27,300.0,10.5,0.413,0.9393,0.1944,0.064

🔹 Procesando: INTC ...
⚡ OPORTUNIDAD: INTC (PUT) | Barrera: 41.26
⚡ Mov. en hrs: INTC (BAJISTA) | Barrera: 41.19
--- FIltrando noticias para INTC ---
⚠️ Ninguna noticia pasó el filtro de relevancia para INTC.

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,INTC,PUT,43.42,41.26,41.19,2026-03-20,42.5,2.0,0.722,0.9054,0.7685,0.0

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,INTC,PUT,43.42,41.26,41.19,2026-03-27,42.0,2.34,0.697,0.8795,0.7626,0.0

🔹 Procesando: AMD ...
⚡ OPORTUNIDAD: AMD (CALL) | Barrera: 201.46
⚡ Mov. en hrs: AMD (ALCISTA) | Barrera: 197.50
--- FIltrando noticias para AMD ---
The Donald Trump administration is reportedly considering a new framework for exporting advanced artificial intelligence chips that could require foreign governments to invest in U.S. data centers. Proposed AI Chip Export Framework U.S. officials are debating a regulatory framework to govern exports of advanced AI chips produced by companies such as Nvidia Corp and Advanced Micro Devices, Inc., Reuters reported on Thursday, citing a document. Under the proposal, countries seeking large quantitie
Meta Platforms signed multi year AI chip and infrastructure agreements with Nvidia, AMD, and Google to support its next generation AI systems. The company is pursuing a major data center expansion, including a potential site in Texas that previously had interest from Oracle and OpenAI, with Nvidia involved in facilitating a possible lease. Meta also secured a content licensing deal with News Corp to use premium news content for AI training across its platforms. For investors tracking...
Riot Platforms (NasdaqCM:RIOT) has acquired full ownership of its Rockdale, Texas site, removing future lease obligations. The company plans to develop the Rockdale facility into high-capacity AI and data center infrastructure. Riot has signed a 10 year anchor lease with AMD to host AI and high performance computing workloads. The company is aiming to leverage its 1.7 gigawatt Texas power portfolio to support large scale data center operations. Riot Platforms, best known as a pure play...
Advanced Micro Devices, Inc. (NASDAQ:AMD) is one of the best stocks with huge upside potential to buy according to Reddit. Advanced Micro Devices, Inc. (NASDAQ:AMD) announced on March 2 the expansion of the Ryzen™ AI portfolio with the launch of the AMD Ryzen™ AI 400 Series and Ryzen™ AI PRO 400 Series desktop processors. Management […]
Advanced Micro Devices Inc. (NASDAQ:AMD) is one of the 13 Most Profitable Growth Stocks to Buy Right Now. On March 2, UBS analyst Timothy Arcuri reiterated a Buy rating on Advanced Micro Devices Inc. (NASDAQ:AMD) while lowering the firm’s price target. He reduced the firm’s price target on the stock from $330 to $310. The […]
AMD (NasdaqGS:AMD) announced a multi year, gigawatt scale AI infrastructure partnership with Meta Platforms, valued at more than $100b. The agreement includes custom Instinct GPUs, performance warrants, and broad infrastructure collaboration across Meta's AI data centers. AMD also introduced Ryzen AI 400 Series chips for AI focused PCs and expanded research and telecom alliances in Canada, Vietnam, and with Wind River. For investors watching Advanced Micro Devices at a share price of...
Advanced Micro Devices Inc. is fortifying its domestic footprint and market sentiment despite broader sector volatility. This week, the company's momentum score climbed from 88.93 to 90.84, placing it within the top 10% of the market as it secures critical infrastructure and product milestones. Strategic Validation And Elite Rankings While the stock faces short-term bearish pressure—down 7.26% YTD—its underlying fundamentals remain robust. AMD currently boasts an exceptional quality score of 93.
Advanced Micro Devices, Inc. (NASDAQ:AMD) is among the ARK Invest Stock Portfolio: Top 10 Stock Picks for 2026. The stock remains on analysts’ radar and sports a Moderate Buy rating, with an upside potential of 42% as of the close on March 4. Recent updates include UBS analyst Timothy Arcuri on March 2 reiterating a […]

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,AMD,CALL,192.43,201.46,197.5,2026-03-20,197.5,7.15,0.664,0.7859,0.3688,0.7761

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,AMD,CALL,192.43,201.46,197.5,2026-03-27,195.0,10.35,0.649,0.8815,0.3971,0.7761

==================================================
🚀 INICIANDO INFERENCIA SECTOR: BANKS
==================================================
✅ Modelos cargados para BANKS
🔹 Procesando: BAC ...
⚡ OPORTUNIDAD: BAC (CALL) | Barrera: 49.86
⚡ Mov. en hrs: BAC (ALCISTA) | Barrera: 49.50
--- FIltrando noticias para BAC ---
Bank of America (NYSE:BAC) is under scrutiny after its chief equity strategist highlighted systemic risk tied to leveraged loans and bank-loan ETFs. The bank publicly opposed a proposed US Crypto Bill compromise, citing concerns about potential risks to its deposit base. Senior insiders, including the Chief People Officer and a Co President, recently sold shares, adding another datapoint for investors tracking governance and risk signals. As one of the largest US universal banks, NYSE:BAC...
Bank of America made a bold call on Marvell Technology (MRVL) Friday morning, flipping its rating from neutral to buy and lifting its price target to $110 from $90. The move came hours after Marvell reported blowout fiscal fourth-quarter results that sent shares surging more than 16%. The upgrade ...
With Bank of America renewing its bullish stance on Tesla, is now the right time for investors to buy the stock?

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,BANKS,BAC,CALL,48.64,49.86,49.5,2026-03-20,49.0,1.27,0.409,0.9039,0.7131,0.3365

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,BANKS,BAC,CALL,48.64,49.86,49.5,2026-03-27,49.0,1.58,0.395,0.9178,0.7167,0.3365

🔹 Procesando: JPM ...
⚡ OPORTUNIDAD: JPM (CALL) | Barrera: 296.21
⚡ Mov. en hrs: JPM (ALCISTA) | Barrera: 293.98
--- FIltrando noticias para JPM ---
There is a lot to like about the JPMorgan Equity Premium Income ETF (NYSEARCA:JEPI). For a strategy that combines active stock selection with derivatives, it is priced reasonably at a 0.35% expense ratio. The fund’s portfolio manager, Hamilton Reiner, has largely delivered on the strategy’s core promise: lower volatility than the broad market while generating ... Beyond JEPI: 2 Next-Gen Income ETFs That Are Quietly Outperforming JPMorgan’s Crown Jewel in 2026
MercadoLibre, Inc. (NASDAQ:MELI) is one of the best stocks with huge upside potential to buy according to Reddit. JPMorgan cut the price target on MercadoLibre, Inc. (NASDAQ:MELI) to $2,650 from $2,800 on March 3, maintaining an Overweight rating on the shares and telling investors that it is remaining “constructive” on the shares post earnings. However, […]
Blackstone Inc. (NYSE:BX) is one of the best stocks with huge upside potential to buy according to Reddit. JPMorgan cut the price target on Blackstone Inc. (NYSE:BX) to $122 from $158 on March 3, maintaining a Neutral rating on the shares. It stated that the company’s BCRED, the largest non-traded business development company and flagship […]
GeoPark’s updated fair value estimate has moved slightly, with the price target adjusted from US$11.32 per share to US$11.40 per share. JPMorgan’s revised US$10.50 price target sits below that figure, and recent commentary shows analysts balancing confidence in execution with concerns about valuation risk. As you read on, you will see how these views fit together and what they could mean for how you track GeoPark’s evolving story. Analyst Price Targets don't always capture the full story...

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,BANKS,JPM,CALL,289.48,296.21,293.98,2026-03-20,292.5,6.4,0.371,0.863,0.3232,0.6115

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,BANKS,JPM,CALL,289.48,296.21,293.98,2026-03-27,295.0,7.3,0.369,0.8065,0.3079,0.6115

🔹 Procesando: WFC ...
⚡ OPORTUNIDAD: WFC (CALL) | Barrera: 82.89
⚡ Mov. en hrs: WFC (ALCISTA) | Barrera: 82.25
--- FIltrando noticias para WFC ---
Zscaler, Inc. (NASDAQ:ZS) is one of the cheap AI stocks to buy in 2026. On March 3, 2026, Wells Fargo initiated coverage of Zscaler with an Overweight rating and a $200 price target. Wells Fargo analyst sees a favorable entry point after recent “noise” tied to Red Canary, while expecting Zscaler’s core business to remain […]
Tenable Holdings, Inc. (NASDAQ:TENB) is one of the cheap AI stocks to buy in 2026. On March 3, 2026, Wells Fargo initiated coverage of Tenable Holdings, Inc. with an Equal Weight rating and a $13 price target. Wells Fargo said Tenable holds a 27% share of the vulnerability management market, and noted that the company’s […]
SentinelOne, Inc. (NYSE:S) is one of the cheap AI stocks to buy in 2026. On March 3, 2026, Wells Fargo initiated coverage of SentinelOne with an Equal Weight rating and a $13 price target, with The Fly identifying Richard Poland as the analyst. Reports summarizing the note said Wells Fargo sees SentinelOne as a meaningful […]
In late February 2026, Wells Fargo announced a series of new fixed-rate note offerings across maturities out to 2046, filed a US$3.41 billion employee stock ownership plan-related common stock shelf registration, and moved to redeem all remaining Series BB preferred shares on March 16, 2026. These capital moves arrive just as the Federal Reserve has terminated its 2018 consent order against Wells Fargo, leaving the bank without outstanding Fed enforcement actions for the first time in 15...
Urban Outfitters Inc. (NASDAQ:URBN) is one of the 15 Most Undervalued NASDAQ Stocks to Buy According to Wall Street Analyst. Wells Fargo, on February 26, reduced its target price on Urban Outfitters by 6.3% to $75 (from $80), while retaining the firm’s Equal Weight call on the stock. The firm liked what it saw in […]
Since September 2025, Wells Fargo has been in a holding pattern, posting a small return of 4.1% while floating around $82.37.
The Federal Reserve closes its 2018 enforcement action against WFC, ending years of oversight from the fake-account scandal.
Recently, Zacks.com users have been paying close attention to Wells Fargo (WFC). This makes it worthwhile to examine what the stock has in store.

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,BANKS,WFC,CALL,80.42,82.89,82.25,2026-03-20,82.0,1.74,0.417,0.7744,0.8176,0.2206

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,BANKS,WFC,CALL,80.42,82.89,82.25,2026-03-27,82.0,2.24,0.401,0.8113,0.8243,0.2206

🔹 Procesando: C ...
⚡ OPORTUNIDAD: C (CALL) | Barrera: 110.10
⚡ Mov. en hrs: C (ALCISTA) | Barrera: 108.85
--- FIltrando noticias para C ---
Wayfair Inc. (NYSE:W) is one of the 10 best retail stocks with huge upside potential. On February 26, Citi reduced the firm’s price target on Wayfair Inc. (NYSE:W) from $135 to $110. The firm maintained its Buy rating on the shares, which still offer an upside potential of almost 40% despite the downward revision. Citi […]
UDR (UDR) is back on investors’ radar as recent analyst calls, reflecting mixed views on growth, rental trends, and dividend resilience, now converge with upcoming CEO remarks at Citi’s Miami Global Property Conference. See our latest analysis for UDR. UDR’s share price has been fairly range bound in the short term, with a 90 day share price return of 5.82% and a 1 year total shareholder return decline of 12.42%. Recent analyst revisions and CEO commentary at the conference could be important...
Shares of global financial services giant Citigroup (NYSE:C) fell 2.5% in the afternoon session after the stock fell amid broader market jitters centered on the health of the private credit market, which weighed on the entire financial sector.
Citigroup (C) reached $106.53 at the closing of the latest trading day, reflecting a -2.22% change compared to its last close.

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,BANKS,C,CALL,106.53,110.1,108.85,2026-03-20,108.0,3.05,0.482,0.8495,0.0456,-0.4061

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,BANKS,C,CALL,106.53,110.1,108.85,2026-03-27,108.0,3.75,0.456,0.8693,0.0467,-0.4061

🔹 Procesando: XLF ...
⚡ OPORTUNIDAD: XLF (CALL) | Barrera: 51.32
⚡ Mov. en hrs: XLF (ALCISTA) | Barrera: 51.27
--- FIltrando noticias para XLF ---
Financial stocks were leaning lower pre-bell Friday, with the State Street Financial Select Sector S
The broad market exchange-traded fund SPDR S&P 500 ETF Trust (SPY) was down 0.5% and the actively tr

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,BANKS,XLF,CALL,50.57,51.32,51.27,2026-03-20,51.0,1.18,0.377,0.8872,0.0022,-0.9963

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,BANKS,XLF,CALL,50.57,51.32,51.27,2026-03-27,51.0,1.03,0.267,0.8918,0.0022,-0.9963

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,BANKS,XLF,CALL,50.57,51.32,51.27,2026-03-31,51.0,2.99,0.63,0.9085,0.0023,-0.9963

🔹 Procesando: TNA ...
⚡ OPORTUNIDAD: TNA (CALL) | Barrera: 49.42
⚡ Mov. en hrs: TNA (ALCISTA) | Barrera: 47.76
--- FIltrando noticias para TNA ---
The Direxion Daily Small Cap Bull 3X Shares ETF is a triple-leveraged small-cap ETF.  If the Russell 2000 performs well, it could deliver incredible returns.  If you're bullish on small-cap stocks, it might seem like a good idea to buy shares of a leveraged ETF like the Direxion Daily Small Cap Bull 3X Shares ETF (NYSEMKT: TNA) in order to magnify your returns.

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,BANKS,TNA,CALL,46.37,49.42,47.76,2026-03-20,48.0,2.77,0.994,0.7804,0.7105,0.3978

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,BANKS,TNA,CALL,46.37,49.42,47.76,2026-03-27,48.0,3.3,0.924,0.7946,0.7141,0.3978

==================================================
🚀 INICIANDO INFERENCIA SECTOR: MINING
==================================================
✅ Modelos cargados para MINING
🔹 Procesando: GLD ...
⚡ OPORTUNIDAD: GLD (PUT) | Barrera: 464.73
⚡ Mov. en hrs: GLD (BAJISTA) | Barrera: 464.73
--- FIltrando noticias para GLD ---
Gold spent most of 2025 and early 2026 acting like the one asset that couldn’t be rattled. Then tariff escalation shook the foundation. The SPDR Gold Trust (GLD) slipped 2.43% over the past week even as the fund sits on a 19.1% year-to-date gain and a 75.96% return over the past year. Even the most ... GLD’s $75 Billion Couldn’t Shield It From the Tariff-Driven Selloff
Gold traded higher midafternoon on Friday but remained under its record high as the metal fails to r
Gold traded higher early on Friday but remained under its record high as the metal fails to receive
The broad market exchange-traded fund SPDR S&P 500 ETF Trust (SPY) was down 0.5% and the actively tr
One of the standout performers in the gold mining space this year, IAMGOLD (NYSE:IAG), has seen its shares jump 28.38% year-to-date and an extraordinary 273% over the past twelve months. The question analysts and observers are asking: Is this a fundamentals story, or is IAMGOLD simply riding gold’s coattails? The honest answer is both as ... IAMGOLD’s 273% Run Has a Real Reason Behind It
The precious metal isn't turning out to be the haven it was supposed to be amid the geopolitical uncertainty.
The broad market exchange-traded fund SPDR S&P 500 ETF Trust (SPY) was down 0.2% and the actively tr
Gold reached an all-time high near $5,400 following reports of joint U.S.-Israeli strikes on Iranian nuclear and missile sites, threatening oil flows through the Strait of Hormuz. WTI crude surged to more than $76 per barrel, its highest level in more than a year, amplifying safe-haven demand. With some analysts targeting gold well over $6,000, ... With Iran Sending Gold Over $5,000, the Best Gold Stocks and ETFs to Buy Now
(Updates prices.) Gold edged higher midafternoon on Wednesday, rebounding from a day-prior drop o

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,MINING,GLD,PUT,473.51,464.73,464.73,2026-03-20,469.0,9.8,0.35,0.8815,0.4359,0.0254

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,MINING,GLD,PUT,473.51,464.73,464.73,2026-03-27,469.0,12.1,0.332,0.9027,0.4425,0.0254

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,MINING,GLD,PUT,473.51,464.73,464.73,2026-03-31,469.0,12.65,0.314,0.9043,0.443,0.0254

🔹 Procesando: SLV ...
🔹 Procesando: NEM ...
🔹 Procesando: HL ...
⚡ OPORTUNIDAD: HL (CALL) | Barrera: 21.98
⚡ Mov. en hrs: HL (ALCISTA) | Barrera: 20.45
--- FIltrando noticias para HL ---
Abitibiwinni First Nation is calling on Hecla Mining and Orezone Gold to respect Aboriginal rights in the planned sale of the Casa Berardi Mine and Hecla Quebec subsidiary. The First Nation is seeking formal engagement on sustainable development, environmental protections, and impacts on culturally important species tied to the mine site. The Casa Berardi Mine sits on Abitibiwinni traditional territory, putting Indigenous rights and ESG considerations at the center of this transaction. For...
AG's silver-equivalent output jumps 37% in Q4, fueled by the Gatos Silver deal and record mine performance in Mexico.
HL ramps silver output, cuts leverage and reshapes its portfolio as ASM lifts production and earnings outlook.
Gold and silver prices remain in a long-term uptrend. These three mining stocks offer leveraged exposure to rising metals demand and improving fundamentals
Hecla Mining Co. (HL) is one of the oldest companies listed on the New York Stock Exchange, and it was one of 2025's big winners, up a whopping 295% as silver prices soared nearly to $71.60 per troy ounce. The bloom has come off silver, at least in the short term. It's tumbled nearly 38% from its ...
Hecla Mining (NYSE:HL) has agreed to sell its Casa Berardi gold mine as part of a shift toward a silver focused business model. The company reported record financial results alongside this portfolio change, which includes a smaller debt position. Management plans to allocate nearly double the capital to exploration and pre development projects, with a particular emphasis on Nevada. Hecla Mining, a long standing precious metals producer, is sharpening its focus on silver by exiting its Casa...
Hecla Mining Co (HL) reports a record $1.4 billion revenue and outlines strategic plans for silver production growth amidst challenges.
Hecla Mining (NYSE:HL) executives highlighted record financial results in 2025 and outlined a strategy centered on expanding silver exposure and maintaining capital discipline, according to the company’s fourth-quarter and full-year 2025 conference call. Record 2025 results and balance sheet deleve

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,MINING,HL,CALL,20.39,21.98,20.45,2026-03-20,21.0,1.34,0.99,0.8028,0.9566,0.8679

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,MINING,HL,CALL,20.39,21.98,20.45,2026-03-27,21.0,1.63,0.887,0.8126,0.9571,0.8679

🔹 Procesando: PAAS ...
⚡ OPORTUNIDAD: PAAS (PUT) | Barrera: 56.42
⚡ Mov. en hrs: PAAS (BAJISTA) | Barrera: 55.31
--- FIltrando noticias para PAAS ---
Pan American Silver (TSX:PAAS) reported major exploration discoveries at its La Colorada mine, adding multiple new high grade silver, gold and base metal veins. The company says these finds increase resource potential at La Colorada and support a phased development approach for the underground operation. The update points to an expanded vein system that could support a longer mine life and different development options for the asset. For investors watching TSX:PAAS, the La Colorada news...
Pan American Silver Corp. (NYSE:PAAS) is one of the best Canadian value stocks to buy. On February 18, Pan American Silver reported financial results for 2025, fueled by strong operational performance and high metal prices. The company achieved net earnings of $980 million for the year, with Q4 earnings alone reaching $452 million. This profitability […]
Pan American Silver (PAAS.TO, PAAS) on Wednesday said that the Toronto Stock Exchange accepted its n
Pan American Silver Corp. reported fourth-quarter 2025 sales of US$1,179 million and net income of US$452 million, with full-year 2025 sales of US$3.62 billion and net income of US$978 million, and declared a US$0.18 per-share cash dividend for the quarter, now paid. The results highlight a substantial year-over-year improvement in earnings per share and reflect higher production, including contributions from the Juanicipio mine, alongside an increased dividend payout. Next, we’ll examine...
Pan American Silver stock: why the recent performance has investors watching Pan American Silver (TSX:PAAS) has been on investors’ radar after a recent share price move, with the stock showing a 13.5% return over the past month and 35.9% over the past 3 months. See our latest analysis for Pan American Silver. While the 1-day share price return of an 8.15% decline and 7-day share price return of a 6% decline show some near-term volatility at around CA$84.19, the 1-year total shareholder return...
Canadian-based silver, gold, and zinc producer Pan American Silver's stock is up more than 30% so far this year.
AG stands out against PAAS with record output, rising estimates and strong cash flow, even as both ride higher silver prices.
AG's silver-equivalent output jumps 37% in Q4, fueled by the Gatos Silver deal and record mine performance in Mexico.

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,MINING,PAAS,PUT,59.56,56.42,55.31,2026-03-20,58.0,2.65,0.74,0.8786,0.008,-0.8021

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,MINING,PAAS,PUT,59.56,56.42,55.31,2026-03-27,58.0,3.1,0.698,0.9141,0.0084,-0.8021

🔹 Procesando: NUE ...
⚡ OPORTUNIDAD: NUE (CALL) | Barrera: 170.79
⚡ Mov. en hrs: NUE (ALCISTA) | Barrera: 170.79
--- FIltrando noticias para NUE ---
What Nucor’s Recent Performance Tells You About the Stock Nucor (NUE) has drawn attention after recent share price moves, with a 1 day return of about a 0.7% decline, a small gain over the past week, and mixed results over the past month and past 3 months. For investors, that mix of short term pullbacks and longer period gains naturally raises the question of how current pricing lines up with the company’s fundamentals, recent profitability, and its role across the steel value chain. See our...
In the closing of the recent trading day, Nucor (NUE) stood at $177.4, denoting a -1.76% move from the preceding trading day.
Nucor Corporation (NYSE:NUE) is among the 10 Best Steel Stocks to Buy Right Now. On February 20, 2026, Reuters reported that Nucor Corporation (NYSE:NUE) chose insider Jack Sullivan as chief financial officer, effective March 1. Sullivan is succeeding Steve Laxton, who was appointed president and chief operating officer at the beginning of the year. Sullivan […]
Nucor (NUE) reported earnings 30 days ago. What's next for the stock? We take a look at earnings estimates for some clues.
Nucor Corporation appointed Jack Sullivan as its new Chief Financial Officer, marking a key change in its senior leadership team. The board authorized a new $4 billion share repurchase program, replacing the prior buyback authorization. The company also announced its 212th consecutive quarterly dividend, extending a long record of regular capital returns. Nucor (NYSE:NUE) is making these moves with its shares trading around $178.85 and a 1-year return of 33.5%. Over the past 5 years, the...
Nucor Corporation (NYSE:NUE) is included among the 14 Best Warren Buffett Dividend Stocks to Buy. On February 20, Nucor Corporation (NYSE:NUE)’s Board of Directors approved its regular quarterly cash dividend of $0.56 per share, which will be paid on May 11, 2026, to shareholders who are on record as of March 31, 2026. This marks the […]
A Norwegian green steel group is in the running to buy Speciality Steels UK (SSUK), Britain's third-biggest producer of the metal, six months after it collapsed into liquidation.  Sky News has learnt that Blastr, which is privately owned, is among a small number of parties which remain talks with the Official Receiver about a deal to buy SSUK, which operates from sites in Rotherham and Sheffield.  Employing well over 1,000 people, SSUK was part of the metals empire of Sanjeev Gupta, the tycoon who is facing financial, legal and regulatory battles on a multitude of fronts.
Nucor Corporation stock has outperformed the broader market over the past year, while analysts remain highly bullish about its prospects.
President Trump is considering rolling back U.S. tariffs on imported steel, a potential shift that could affect pricing power across the sector. Warren Buffett has recently increased his stake in Nucor (NYSE:NUE), adding fresh attention to the stock. Nucor shares last closed at $183.23, with a 1 year return of 35.2% and a 5 year return of 241.3%. Nucor, trading on the NYSE under the ticker NUE, sits at $183.23 after a 1 year return of 35.2% and a 5 year return of 241.3%. Those figures put...

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,MINING,NUE,CALL,168.75,170.79,170.79,2026-03-20,170.0,5.1,0.466,0.9082,0.4157,0.347

🔹 Procesando: CLF ...
⚡ OPORTUNIDAD: CLF (CALL) | Barrera: 10.52
⚡ Mov. en hrs: CLF (ALCISTA) | Barrera: 10.02
--- FIltrando noticias para CLF ---
Cleveland-Cliffs (CLF) has received quite a bit of attention from Zacks.com users lately. Therefore, it is wise to be aware of the facts that can impact the stock's prospects.
Cleveland Cliffs (NYSE:CLF) has changed its board leadership structure. Ralph "Mike" Michael III has been appointed Lead Independent Director. Edilson Camara has been appointed Chairman of the Compensation and Organization Committee. These appointments shift oversight of governance and executive pay to new board leaders. Cleveland Cliffs, an iron ore mining and steel company, is closely watched by investors who pay attention to how capital allocation, risk and management incentives are...
Cleveland-Cliffs Inc. (NYSE:CLF) is among the 10 Best Steel Stocks to Buy Right Now. On February 12, 2026, BofA lowered Cleveland-Cliffs Inc. (NYSE:CLF)’s price objective to $13 from $14.50 while maintaining a Neutral rating. The analyst noted a relatively stretched balance sheet and said a potential partnership with POSCO could significantly improve the company’s financial […]
If you are wondering whether Cleveland-Cliffs is priced attractively right now, this article walks through the numbers so you can judge the value for yourself. The stock recently closed at US$10.66, with returns of 0.1% over 7 days, a 22.5% decline over 30 days, a 21.6% decline year to date and a 1 year return of a 1.7% decline. These moves have kept Cleveland-Cliffs on many investors' watchlists, especially as the stock has also recorded a 53.2% decline over 3 years and a 24.5% decline over...
Why Cleveland-Cliffs is on investors’ radar today Cleveland-Cliffs (CLF) has drawn fresh attention after recent share performance, with the stock showing a 3.5% decline over the past day and double digit declines over the past month and past 3 months. For investors watching the materials sector, those short term moves, together with the company’s current value score of 5 and its latest reported financials, are prompting closer scrutiny of what is currently priced into Cleveland-Cliffs...
VALE's strong output, cost cuts and rising earnings estimates stand out against CLF's losses and auto exposure. Which is the better bet?
Cleveland Cliffs has seen its modeled fair value nudged from US$13.44 to US$13.41, a very small 0.2% adjustment that still matters for how analysts frame upside or downside. That tweak sits alongside a split research narrative, with some analysts pointing to tariff support and auto wins, while others focus on valuation constraints, cost pressures, and insider selling. As you read on, you will see how these shifting targets and arguments shape the evolving story and how you can keep track of...
Cleveland-Cliffs Inc. recently reported fourth-quarter 2025 sales of US$4,313 million with a net loss of US$243 million, and full-year 2025 sales of US$18.61 billion with a net loss of US$1.48 billion, while also completing a US$124.22 million share repurchase of 7,507,249 shares under its April 2024 buyback plan. Alongside these weaker results and larger annual losses, Cleveland-Cliffs continues to attract significant market attention, with high short interest and participation in the BMO...

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,MINING,CLF,CALL,9.83,10.52,10.02,2026-03-20,10.0,0.5,0.74,0.8514,0.7352,0.2522

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,MINING,CLF,CALL,9.83,10.52,10.02,2026-03-27,10.0,0.64,0.768,0.8626,0.7379,0.2522

✅ Resultados procesados y guardados en: Inference_Results.xlsx

,Fecha,Sector,Ticker,Tipo,Precio Actual,Barrera,Barrera a 10 hrs,Vencimiento,Strike,Ask,IV,Prob. Mercado,Prob. Final (Bayes),Sentimiento Score
0,2026-03-09,TECH,QQQ,CALL,599.75,608.86,607.62,2026-03-20,604.0,11.89,0.320,0.8957,0.7561,0.3290
1,2026-03-09,TECH,QQQ,CALL,599.75,608.86,607.62,2026-03-27,604.0,14.00,0.293,0.9142,0.7604,0.3290
2,2026-03-09,TECH,QQQ,CALL,599.75,608.86,607.62,2026-03-31,604.0,14.91,0.281,0.9216,0.7621,0.3290
3,2026-03-09,TECH,META,CALL,644.86,662.24,660.25,2026-03-20,652.5,15.05,0.397,0.8523,0.0760,0.0140
4,2026-03-09,TECH,META,CALL,644.86,662.24,660.25,2026-03-27,655.0,17.95,0.383,0.8412,0.0751,0.0140
5,2026-03-09,TECH,AAPL,PUT,257.46,251.64,250.33,2026-03-20,255.0,5.45,0.357,0.8843,0.0716,-0.0358
6,2026-03-09,TECH,AAPL,PUT,257.46,251.64,250.33,2026-03-27,255.0,6.50,0.329,0.9008,0.0730,-0.0358
7,2026-03-09,TECH,AMZN,CALL,213.21,219.52,219.52,2026-03-20,217.5,4.90,0.441,0.7786,0.1871,-0.3963
8,2026-03-09,TECH,AMZN,CALL,213.21,219.52,219.52,2026-03-27,215.0,7.55,0.434,0.9105,0.2136,-0.3963
9,2026-03-09,TECH,TSLA,CALL,396.73,407.48,405.43,2026-03-20,402.5,11.60,0.495,0.8449,0.6295,0.0730
10,2026-03-09,TECH,TSLA,CALL,396.73,407.48,405.43,2026-03-27,400.0,15.90,0.482,0.9125,0.6492,0.0730
11,2026-03-09,TECH,NVDA,CALL,177.82,183.50,181.58,2026-03-20,180.0,6.45,0.573,0.8737,0.0760,0.0000
12,2026-03-09,TECH,NVDA,CALL,177.82,183.50,181.58,2026-03-27,180.0,7.70,0.532,0.8856,0.0770,0.0000
13,2026-03-09,TECH,PLTR,CALL,157.16,163.88,168.35,2026-03-20,160.0,5.75,0.613,0.8344,0.0417,-0.2847
14,2026-03-09,TECH,PLTR,CALL,157.16,163.88,168.35,2026-03-27,160.0,7.25,0.591,0.8528,0.0427,-0.2847
15,2026-03-09,TECH,MSFT,CALL,408.96,415.52,419.72,2026-03-20,412.5,8.80,0.353,0.8810,0.0002,-0.9946
16,2026-03-09,TECH,MSFT,CALL,408.96,415.52,419.72,2026-03-27,410.0,12.40,0.347,0.9655,0.0003,-0.9946
17,2026-03-09,TECH,GOOGL,CALL,298.52,305.27,301.39,2026-03-20,302.5,6.80,0.399,0.8361,0.1747,0.0640
18,2026-03-09,TECH,GOOGL,CALL,298.52,305.27,301.39,2026-03-27,300.0,10.50,0.413,0.9393,0.1944,0.0640
19,2026-03-09,TECH,INTC,PUT,43.42,41.26,41.19,2026-03-20,42.5,2.00,0.722,0.9054,0.7685,0.0000
20,2026-03-09,TECH,INTC,PUT,43.42,41.26,41.19,2026-03-27,42.0,2.34,0.697,0.8795,0.7626,0.0000
21,2026-03-09,TECH,AMD,CALL,192.43,201.46,197.50,2026-03-20,197.5,7.15,0.664,0.7859,0.3688,0.7761
22,2026-03-09,TECH,AMD,CALL,192.43,201.46,197.50,2026-03-27,195.0,10.35,0.649,0.8815,0.3971,0.7761
23,2026-03-09,BANKS,BAC,CALL,48.64,49.86,49.50,2026-03-20,49.0,1.27,0.409,0.9039,0.7131,0.3365
24,2026-03-09,BANKS,BAC,CALL,48.64,49.86,49.50,2026-03-27,49.0,1.58,0.395,0.9178,0.7167,0.3365
25,2026-03-09,BANKS,JPM,CALL,289.48,296.21,293.98,2026-03-20,292.5,6.40,0.371,0.8630,0.3232,0.6115
26,2026-03-09,BANKS,JPM,CALL,289.48,296.21,293.98,2026-03-27,295.0,7.30,0.369,0.8065,0.3079,0.6115
27,2026-03-09,BANKS,WFC,CALL,80.42,82.89,82.25,2026-03-20,82.0,1.74,0.417,0.7744,0.8176,0.2206
28,2026-03-09,BANKS,WFC,CALL,80.42,82.89,82.25,2026-03-27,82.0,2.24,0.401,0.8113,0.8243,0.2206
29,2026-03-09,BANKS,C,CALL,106.53,110.10,108.85,2026-03-20,108.0,3.05,0.482,0.8495,0.0456,-0.4061
30,2026-03-09,BANKS,C,CALL,106.53,110.10,108.85,2026-03-27,108.0,3.75,0.456,0.8693,0.0467,-0.4061
31,2026-03-09,BANKS,XLF,CALL,50.57,51.32,51.27,2026-03-20,51.0,1.18,0.377,0.8872,0.0022,-0.9963
32,2026-03-09,BANKS,XLF,CALL,50.57,51.32,51.27,2026-03-27,51.0,1.03,0.267,0.8918,0.0022,-0.9963
33,2026-03-09,BANKS,XLF,CALL,50.57,51.32,51.27,2026-03-31,51.0,2.99,0.630,0.9085,0.0023,-0.9963
34,2026-03-09,BANKS,TNA,CALL,46.37,49.42,47.76,2026-03-20,48.0,2.77,0.994,0.7804,0.7105,0.3978
35,2026-03-09,BANKS,TNA,CALL,46.37,49.42,47.76,2026-03-27,48.0,3.30,0.924,0.7946,0.7141,0.3978
36,2026-03-09,MINING,GLD,PUT,473.51,464.73,464.73,2026-03-20,469.0,9.80,0.350,0.8815,0.4359,0.0254
37,2026-03-09,MINING,GLD,PUT,473.51,464.73,464.73,2026-03-27,469.0,12.10,0.332,0.9027,0.4425,0.0254
38,2026-03-09,MINING,GLD,PUT,473.51,464.73,464.73,2026-03-31,469.0,12.65,0.314,0.9043,0.4430,0.0254
39,2026-03-09,MINING,HL,CALL,20.39,21.98,20.45,2026-03-20,21.0,1.34,0.990,0.8028,0.9566,0.8679
40,2026-03-09,MINING,HL,CALL,20.39,21.98,20.45,2026-03-27,21.0,1.63,0.887,0.8126,0.9571,0.8679
41,2026-03-09,MINING,PAAS,PUT,59.56,56.42,55.31,2026-03-20,58.0,2.65,0.740,0.8786,0.0080,-0.8021
42,2026-03-09,MINING,PAAS,PUT,59.56,56.42,55.31,2026-03-27,58.0,3.10,0.698,0.9141,0.0084,-0.8021
43,2026-03-09,MINING,NUE,CALL,168.75,170.79,170.79,2026-03-20,170.0,5.10,0.466,0.9082,0.4157,0.3470
44,2026-03-09,MINING,CLF,CALL,9.83,10.52,10.02,2026-03-20,10.0,0.50,0.740,0.8514,0.7352,0.2522
45,2026-03-09,MINING,CLF,CALL,9.83,10.52,10.02,2026-03-27,10.0,0.64,0.768,0.8626,0.7379,0.2522